---
title: "Fire_04_Calibration_PiecewiseLinearRegression"
author: "Femke Keij S2647168"
date: "2023-02-22"
output: pdf_document
---

## Piecewise linear regression
Calculate the piecewise linear regression fit for each of the directions and each of the sample sizes
```{r}
# create data frame to store the RMSEs for each sample size and direction
piecewise_reg_errors <- bind_cols(rep(n, 2),
                                  c(rep(4, length(n)),
                                         rep(8, length(n))),
                                  rep(NA, 2 * length(n)))
colnames(piecewise_reg_errors) <- c("N", "direction", "RMSE")

for(i in 2:length(n)){
  fit4 <- PiecewiseRegFitting(n = n[i],
                             training = filter(fire_train,
                                               direction == "4"),
                             formula = "burn_percentage ~ density")
  fit8 <- PiecewiseRegFitting(n = n[i],
                              training = filter(fire_train,
                                                direction == "8"),
                              formula = "burn_percentage ~ density")
  
  piecewise_reg_errors[i] <- 
    rmse(fit4,
         data = filter(fire_test, direction == "4"))
  piecewise_reg_errors[i + length(n)] <-
    rmse(fit8, 
         data = filter(fire_test, direction == "8"))
  #piecewise_reg_errors[i] <- 
   # PiecewiseRegError(fit = fit4, 
    #                  test = filter(fire_test, direction == "4"),
     #                 y = 'burn_percentage')
  #piecewise_reg_errors[i + length(n)] <- 
   # PiecewiseRegError(fit = fit8,
    #                  test = filter(fire_test, direction == "8"),
     #                 y = 'burn_percentage')
}
```

```{r}
piecewise_fit_4 <- lm(burn_percentage ~ density,
                      data = filter(fire_train, direction == "4"))

segmented_fit_4 <- segmented(piecewise_fit_4, 
                           seg.Z = ~ density,
                           psi = 59)
```

Plot the fits
```{r}
newdat_4 <- as.data.frame(cbind(fire_four_output$density,
                 broken.line(segmented_fit_4)$fit))
newdat_8 <- as.data.frame(cbind(fire_eight_output$density,
                 broken.line(segmented_fit_8)$fit))

ggplot() +
  geom_point(data = fire_train, aes(x = density, y = burn_percentage,
                                    color = direction)) +
  geom_line(data = newdat_4, aes(x = newdat_4[, 1], y = newdat_4[, 2]),
            colour = 'red') +
  geom_line(data = newdat_8, aes(x = newdat_8[, 1], y = newdat_8[, 2]),
            colour = 'blue') +
  labs(x = "density", y = "% burned trees at last tick")
```

Calculate the error (separately for each direction)
```{r}
# predict values in the test set, using the segmented fit
predict_piecewise_4 <- predict.segmented(segmented_fit_4,
                                         newdat = filter(fire_test,
                                                         direction == "4"))
predict_piecewise_8 <- predict.segmented(segmented_fit_8,
                                         newdat = filter(fire_test,
                                                         direction == "8"))

piecewise_rmse_4 <- sqrt(mean((filter(fire_test, direction == "4")$burn_percentage - predict_piecewise_4)^2))

piecewise_rmse_8 <- sqrt(mean((filter(fire_test, direction == "8")$burn_percentage - predict_piecewise_8)^2))
```

