---
title: "Fire_04_Calibration_RandomForest"
author: "Femke Keij S2647168"
date: "2023-02-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# for random forest
library(randomForest)
```

## Random forest
Fit the random forest for different sample sizes
```{r}
random_forest_errors <- matrix(NA, ncol = 2, nrow = length(n))
random_forest_errors[, 1] <- n
colnames(random_forest_errors) <- c("N", "RMSE")

for(i in 1:length(n)){
  # fit the random forest
  fit <- RandomForestFitting(n = n[i],
                             training = fire_train,
                             formula = "burn_percentage ~ density + direction")
  random_forest_errors[i, 2] <- RandomForestError(fit = fit,
                                               test = fire_test,
                                               y = 'burn_percentage')
}
```

Repeat each random forest 10 times to take out some of the variability:
```{r}
random_forest_errors_multiple <- matrix(NA,
                                        ncol = 2,
                                        nrow = 10 * length(n))
random_forest_errors_multiple[, 1] <- rep(n, 10)
colnames(random_forest_errors_multiple) <- c("N", "RMSE")

for(i in 1:nrow(random_forest_errors_multiple)){
  # fit the random forest
  fit <- RandomForestFitting(n = random_forest_errors_multiple[i, 1],
                             training = fire_train,
                             formula = "burn_percentage ~ density + direction")
  random_forest_errors_multiple[i, 2] <- RandomForestError(fit = fit,
                                                           test = fire_test,
                                                           y = "burn_percentage")
}
```

Show the error progression for different sample sizes
```{r}
as.data.frame(random_forest_errors_multiple) %>%
  group_by(N) %>%
  summarise(error = mean(RMSE),
            max = max(RMSE),
            min = min(RMSE)) %>%
  ggplot(aes(x = N, y = error)) +
  labs(x = "sample size", y = "mean RMSE over 10 random forests",
       title = "Root Mean Square Error in random forest",
       caption = "Blue dots are RMSE for a single random forest \n
       Green dots are mean RMSE over 10 different random forests \n
       Grey bands indicate minimum and maximum RMSE within the 10 random forests") +
  geom_point(colour = "dark green") +
  geom_point(data = as.data.frame(random_forest_errors),
             aes(x = N, y = RMSE), colour = "blue") +
  geom_ribbon(aes(ymin = min, ymax = max), alpha = 0.3)
```

Show what a random forest might look like for a single run with the full training sample
```{r}
random_forest <- randomForest(burn_percentage ~ density + direction,
                              data = fire_train)

plot(random_forest)

# plot the tree itself
```

## Bagging
Fit the bagging for different sample sizes
```{r}
bagging_errors <- matrix(NA, ncol = 2, nrow = length(n))
bagging_errors[, 1] <- n
colnames(bagging_errors) <- c("N", "RMSE")

for(i in 1:length(n)){
  # fit the bagging
  fit <- BaggingFitting(
    n = n[i],
    training = fire_train,
    formula = "burn_percentage ~ density + direction",
    p = 2)
  # calculate the bagging errors
  bagging_errors[i, 2] <- BaggingError(fit = fit,
                                       test = fire_test,
                                       y = 'burn_percentage')
}
```

Plot the bagging errors
```{r}
as.data.frame(bagging_errors) %>%
  ggplot(aes(x = N, y = RMSE)) +
  geom_point()
```

## Boosting
