---
title: "trying out regression things"
author: "Femke Keij S2647168"
date: '2022-08-16'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in data:
```{r}
# training data
fire_train <- read_csv(
  'data/processed/fire-training.csv')
fire_train$direction <- as.factor(fire_train$direction)

# test data
fire_test <- read_csv(
  'data/processed/fire-test.csv')
fire_test$direction <- as.factor(fire_test$direction)
```

Regress:
```{r}
fit_lm_density <- lm(density ~ burn_percentage,
                     data = fire_train)
real_S <- 0.866

pred_density <- predict(fit_lm_density, newdat = fire_test[2, ])

# bootstrapping
for(i in 1:200){
  bootstrap_sample <- fire_train[sample(1:nrow(fire_train),
                                        size = nrow(fire_train),
                                        replace = TRUE), ]
  
  bootstrap_fit_lm <- lm(density ~ burn_percentage,
                         data = bootstrap_sample)
  
  bootstrap_pred_density <- predict(bootstrap_fit_lm,
                                    newdat = fire_test[2, ])
  
  res <- abs(fire_test[2,2] - bootstrap_pred_density)
  hatval <- bootstrap_pred_density
  s_res <- res / sqrt(1 - hatval)
  total <- bootstrap_pred_density + s_res
}

```